package com.depromeet.fragraph.core.ui.select_dialog


const val HIDE_FLAG = -1

const val SAVE_MEMO_DELETE = 0
const val SAVE_MEMO_CONFIRM = 1

const val OUT_SESSION_SAVE = 2
const val OUT_SESSION_EXIT = 3

const val FINISH_SESSION_LEFT = 4
const val FINISH_SESSION_RIGHT = 5

const val HOME_HISTORY_DELETE_CANCEL = 6
const val HOME_HISTORY_DELETE_CONFIRM = 7

const val HOME_HISTORY_EDIT_CANCEL = 8
const val HOME_HISTORY_EDIT_CONFIRM = 9

enum class SelectDialogType constructor(val leftFlag: Int, val rightFlag: Int) {
    MEMO_ON_WRITING(SAVE_MEMO_DELETE, SAVE_MEMO_CONFIRM),
    SESSION_OUT(OUT_SESSION_SAVE, OUT_SESSION_EXIT),
    SESSION_FINISH(FINISH_SESSION_LEFT, FINISH_SESSION_RIGHT),
    HIDE_DIALOG(HIDE_FLAG, HIDE_FLAG),
    HOME_HISTORY_DELETE(HOME_HISTORY_DELETE_CANCEL, HOME_HISTORY_DELETE_CONFIRM),
    HOME_HISTORY_EDIT(HOME_HISTORY_EDIT_CANCEL, HOME_HISTORY_EDIT_CONFIRM),
}